FROM ubuntu
MAINTAINER Joan David Colina <joancolina819@gmail.com>

WORKDIR /home

#Instalmos sudo
RUN apt-get update && apt-get install -y sudo
#Instalamos git
RUN yes | sudo apt-get install git
#Instalamos maven
RUN sudo apt update
RUN yes | sudo apt install maven
RUN mvn -version
#Instalamos java
RUN sudo apt update 
RUN  yes | sudo apt install default-jdk
RUN   java -version
#instalamos wget 
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

#Descargamos minizinc 2.2.3
RUN wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.3.0/MiniZincIDE-2.3.0-bundle-linux-x86_64.tgz
#Descromprimimos el archivo .tgz
RUN tar xf MiniZincIDE-2.3.0-bundle-linux-x86_64.tgz
WORKDIR /home/MiniZincIDE-2.3.0-bundle-linux/bin
#RUN wget https://raw.githubusercontent.com/joancolina819/Coffee-Microservices/master/Reasoning/archivos%20de%20solvers/scrips/ConfiguradorEntorno.sh
#RUN ls
#RUN bash ConfiguradorEntorno.sh
#RUN  sudo -s
#RUN no | sudo dpkg-reconfigure dash
#RUN  export PATH=$PATH:/home/MiniZincIDE-2.3.0-bundle-linux/bin  
#RUN source  ~/.bash_profile  
ENV PATH="/home/MiniZincIDE-2.3.0-bundle-linux/bin:${PATH}"
RUN echo $PATH 
RUN minizinc --solvers
#PATH=$PATH:/Users/Angela/Coffee/apache-maven-3.6.0/bin
#Descargamos Picat
WORKDIR /home
RUN wget http://picat-lang.org/download/picat26_linux64.tar.gz
RUN tar xf picat26_linux64.tar.gz

#Descargamos las librerias de picat
WORKDIR /home/MiniZincIDE-2.3.0-bundle-linux/share/minizinc
RUN wget http://picat-lang.org/flatzinc/picat_globals.tar.gz -O picat_sat
RUN tar xf picat_sat

#Descargando el .msc que necesita minizinc para funcionar
WORKDIR /home/MiniZincIDE-2.3.0-bundle-linux/share/minizinc/solvers
RUN wget https://raw.githubusercontent.com/joancolina819/Coffee-Microservices/master/Reasoning/archivos%20de%20solvers/msc/picat_sat_cmd_line.msc
RUN ls
#Descargando el .sh que necesita picat para funcionar
WORKDIR /home/Picat
RUN wget https://github.com/joancolina819/Coffee-Microservices/blob/master/Reasoning/archivos%20de%20solvers/sh%20files/picat.sh
RUN ls
#Clonamos el repositorio de JminiZinc
WORKDIR /home
RUN git clone https://github.com/siemens/JMiniZinc
RUN ls 
RUN minizinc --solvers